// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttabdmjvlbnfmhpeztct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0YWJkbWp2bGJuZm1ocGV6dGN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1ODA4MTksImV4cCI6MjA2MDE1NjgxOX0.3McuGTbWRSPcKg66U8MGv4W-DeRWGlApILD1ziUOGOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);